name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5


      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure CMake (x64)
        run: cmake --preset clang-x64

      - name: Build (x64)
        run: cmake --build --preset clang-x64-release --verbose

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x86

      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure CMake (x86)
        run: cmake --preset clang-x86

      - name: Build (x86)
        run: cmake --build --preset clang-x86-release --verbose

      - name: Prepare Release folder
        run: md githubrelease

      - name: Copy Binaries (x64)
        run: copy build\release\*.addon64 githubrelease\

      - name: Copy Binaries (x86)
        run: copy build32\release\*.addon32 githubrelease\

      - name: Copy Binaries (Tools)
        run: copy build\release\*.exe githubrelease\

      - name: Put current date into a variable
        run: |
          $NOW=& Get-Date -format yyyy-MM-dd
          echo "NOW=$NOW" >> $env:GITHUB_ENV

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: RenoDX Nightly Build ${{ env.NOW }}
          prerelease: true
          workdir: githubrelease
          tag: nightly-${{ env.NOW }}
