name: Ninja

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.json"
      - "docs/**"
      - "workflow/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.json"
      - "docs/**"
      - "workflow/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure CMake (x64)
        run: cmake --preset ninja-x64

      - name: Build RelWithDebInfo (x64)
        run: cmake --build --preset ninja-x64-relwithdebinfo --verbose

      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure CMake (x86)
        run: cmake --preset ninja-x86

      - name: Build RelWithDebInfo (x86)
        run: cmake --build --preset ninja-x86-relwithdebinfo --verbose
