name: snapshot

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".github/workflows/**"

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Download Slang binaries
        run: |
          curl -L -o slang.zip https://github.com/shader-slang/slang/releases/download/v2025.10.3/slang-2025.10.3-windows-x86_64.zip
          powershell -Command "Expand-Archive -Path slang.zip -DestinationPath slang_temp -Force; if (!(Test-Path -Path .\bin)) { New-Item -ItemType Directory -Path .\bin }; Copy-Item slang_temp\bin\* .\bin -Force; Remove-Item slang_temp -Recurse -Force"

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5


      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure CMake (x64)
        run: cmake --preset clang-x64

      - name: Build (x64)
        run: cmake --build --preset clang-x64-release --verbose

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x86

      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure CMake (x86)
        run: cmake --preset clang-x86

      - name: Build (x86)
        run: cmake --build --preset clang-x86-release --verbose

      - name: Prepare Release folder
        run: md githubrelease

      - name: Copy Schema
        run: copy renodx-metadata-schema.json githubrelease\

      - name: Copy Binaries (x64)
        run: copy build\release\*.addon64 githubrelease\

      - name: Copy Binaries (x86)
        run: copy build32\release\*.addon32 githubrelease\

      - name: Copy Binaries (Tools)
        run: copy build\release\*.exe githubrelease\
      
      - name: Copy Binaries (PDBs)
        run: copy build\release\*.pdb githubrelease\
      
      - name: Generate metadata manifest
        run: node scripts/generate-release-manifest.mjs


      - name: Put current date into a variable
        run: |
          $NOW=& Get-Date -format yyyyMMdd
          echo "NOW=$NOW" >> $env:GITHUB_ENV

      - name: Create a Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: snapshot
          title: RenoDX Snapshot Build
          files: githubrelease/*
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "githubrelease"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: windows-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
